// DebugDrawVar("random", blink.random_timer.timer)
// DebugDrawVar("reload", blink.reload_timer.timer)
// DebugDrawVar("under_attack")
// DebugDrawVar("missiles shots", weapon_missiles.shots_left)
// DebugDrawVar("missiles reload", weapon_missiles.timer.timer)
// DebugDrawVar("missiles burst reload", weapon_missiles.burst_timer.timer)
